### PR TITLE
add rt5682 for CML

### PR DESCRIPTION
**Pull request by zhuyingjiang**
add the rt5682 codec ACPI for CML, this can be the generic for
intel RVP which using rt5682

Signed-off-by: Zhu Yingjiang <yingjiang.zhu@linux.intel.com>

### CODE REVIEW

**Comment by zhuyingjiang** [comment]
@plbossart @lgirdwood Could you add me in this repo, so I can request a reviewer here.

**Comment by plbossart** [comment]
@zhuyingjiang this looks exactly like the one for ICL - even using the same copy/paste mistake, is there really a need to do the same thing twice? @bardliao can you check if we could reuse with ICL?

**Comment by bardliao** [comment]
@plbossart We still lack of GpioInt like [RT5651.asl](https://github.com/plbossart/MinnowBoardMaxFirmware/blob/master/AudioSsdtUpdate/RT5651.asl#L44) for jack detection. I don't know if we can use the same irq configuration for CML and ICL.

**Comment by zhuyingjiang** [comment]
> this looks exactly like the one for ICL - even using the same copy/paste mistake, is there really a need to do the same thing twice?
@plbossart Yes, this is copy from ICL, sorry for have not see the ICL PR. @bardliao Could we make rt5682 the same and add some GPIO specific for Jack detect on every platform? follow the same as the driver, we add sof_rt5682.asl file for common part and add the platform specific in every platform folder.

**Comment by lgirdwood** [comment]
@plbossart I guess we also need a CODEOWNERS for this repo with maybe you and @bardliao ?

**Pull request closed without merging**
